FROM node:15

WORKDIR /app
ENV DOCKERIZE_VERSION v0.7.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
COPY /nodejs/package*.json ./
COPY /nodejs/index.js ./
COPY /nodejs/docker-entrypoint.sh ./docker-entrypoint.sh
RUN chmod +x /app/docker-entrypoint.sh
RUN chmod 777 /app/docker-entrypoint.sh
RUN npm install -y
RUN npm install mysql

EXPOSE 3000

CMD [ "node", "index.js"]
#ENTRYPOINT [ "./docker-entrypoint.sh" ]
