FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d/

# feedback do professor: Aqui podemos deixar apenas desta forma, na linha 3 apagamos o arquivo padrão de configuração do nginx e então copiamos o nosso local.
